site_name: yude's wiki
site_url: https://wiki.yude.jp
site_author: 'yude'
theme:
    name: material
    language: 'ja'
    feature:
      tabs: true

extra_css:
  - css/fonts.css

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized
  - mkdocs-nav-enhancements