site_name: yude.moe Wiki
site_url: https://wiki.yude.moe
site_author: 'yude'
theme:
    name: material
    language: 'ja'
    feature:
      tabs: true

extra_css:
  - css/fonts.css

plugins:
  - search
  - awesome-pages
  - git-revision-date
  - git-committers
  - rss
  - mkdocs-nav-enhancements
  - print-site