site_name: yude's wiki
site_url: https://wiki.yude.jp
site_author: 'yude'
theme:
    name: material
    language: ja
    features:
      - navigation.top

extra_css:
  - css/fonts.css

plugins:
  - search
  - awesome-pages
  - mkdocs-nav-enhancements
